"""Protocol observer V8 — LOAD + VERIFY with embedded test TAP.

Identical to V7 (rewind to offset=0 on header request, supporting
back-to-back LOAD/VERIFY) but the test program is EMBEDDED inline in
this file as a byte tuple. No SD card setup needed — just run.

Embedded program (51 bytes total):
    10 PRINT "test"
    20 GO TO 10
with autorun OFF, so it sits at BASIC ready prompt after LOAD.

Test sequence:
  1. Run this script via Thonny.
  2. Power on TS-2068 (boots via EXROM).
  3. On TS-2068:
       LOAD ""       → loads test program (no autorun)
       VERIFY ""     → V8 rewinds and re-sends; Z80 should report 0 OK
       RUN           → program prints "test" forever (BREAK to stop)

The protocol layer is the same as V6/V7. The only differences here:
  - test.tap is embedded as bytes instead of read from SD
  - SD-related code removed (no SPI/SDCard imports)
"""

import os
import time
import gc
from rp2 import StateMachine, asm_pio, PIO
from machine import Pin, freq

freq(270_000_000)

from TS.tspico_io import TS_IO_DUAL, set_ctrl, sel_bank


# ============================================================================
# Pins + ROM_SM/BANK_SM
# ============================================================================

print("=" * 60)
print("PROTOCOL OBSERVER V8 — embedded test.tap, no SD card needed")
print("=" * 60)

U6_EN   = Pin(12, Pin.OUT, Pin.PULL_UP)
WAIT    = Pin(14, Pin.OUT, Pin.PULL_DOWN)
U10_ENA = Pin(19, Pin.OUT, Pin.PULL_UP)
U13_ENA = Pin(20, Pin.OUT, Pin.PULL_UP)
BE      = Pin(21, Pin.OUT, Pin.PULL_UP)
ROSCS   = Pin(26, Pin.IN,  Pin.PULL_DOWN)
U10_WE  = Pin(27, Pin.OUT, Pin.PULL_UP)
for p in (U6_EN, WAIT, U10_ENA, U13_ENA, BE, U10_WE):
    p.value(1)

rom_sm = StateMachine(4, set_ctrl, freq=150_000_000,
                      in_base=Pin(0, Pin.IN), jmp_pin=Pin(26),
                      set_base=Pin(21, Pin.OUT),
                      out_base=Pin(19, Pin.OUT))
rom_sm.active(1)
bank_sm = StateMachine(5, sel_bank, freq=150_000_000,
                       jmp_pin=Pin(26),
                       out_base=Pin(15, Pin.OUT))
bank_sm.active(1)
rom_sm.put(0x0A)
bank_sm.put(0x01)
print("[SETUP] ROM_SM/BANK_SM running")


# ============================================================================
# Embedded test TAP — no SD card needed
# ============================================================================
# This is the binary contents of test/test.tap (51 bytes): a TAP file
# containing the program
#     10 PRINT "test"
#     20 GO TO 10
# with autorun OFF (HDVARS high byte = 0x80). After LOAD the TS-2068
# sits at the BASIC ready prompt with the program in memory but not
# running — perfect for VERIFY testing.
#
# Generated by test/make_test_tap.py. To re-generate or use a different
# program, edit and re-run that script, then update this byte tuple.
TEST_TAP = bytes((
    0x13, 0x00,                                                                # block 0 prefix: len=19
    0x00, 0x00, 0x74, 0x65, 0x73, 0x74, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,    # type+HDTYPE+name
    0x1A, 0x00, 0x00, 0x80, 0x1A, 0x00, 0x96,                                  # BLEN, ADDR, HDVARS, CRC
    0x1C, 0x00,                                                                # block 1 prefix: len=28
    0xFF, 0x00, 0x0A, 0x08, 0x00, 0xF5, 0x22, 0x74, 0x65, 0x73, 0x74, 0x22,    # data: type, line 10
    0x0D, 0x00, 0x14, 0x0A, 0x00, 0xEC, 0x31, 0x30, 0x0E, 0x00, 0x00, 0x0A,    # line 20 part 1
    0x00, 0x00, 0x0D, 0xE9,                                                    # line 20 end + CRC
))

LOCAL_TAP = "/TMP/temp.tap"

try: os.mkdir("/TMP")
except OSError: pass

with open(LOCAL_TAP, "wb") as f:
    f.write(TEST_TAP)
print("[SETUP] wrote embedded test.tap (%d bytes) to %s" % (
    len(TEST_TAP), LOCAL_TAP))


# ============================================================================
# Pre-open TAP file (we'll read each block lazily as Z80 requests it)
# ============================================================================

arch = open(LOCAL_TAP, "rb")
print("[SETUP] pre-opened %s" % LOCAL_TAP)


# ============================================================================
# Start MQ + pre-load status
# ============================================================================

MQ = StateMachine(0, TS_IO_DUAL, freq=30_000_000,
                  out_base=Pin(2, Pin.OUT),
                  in_base=Pin(2, Pin.IN),
                  jmp_pin=Pin(11),
                  sideset_base=Pin(12, Pin.OUT))
MQ.active(1)
MQ.exec("mov(y, invert(null))")
print("[SETUP] MQ active, Y=READY")

n = 0
last = time.ticks_ms()
while time.ticks_diff(time.ticks_ms(), last) < 300:
    if MQ.rx_fifo() > 0:
        MQ.get()
        n += 1
        last = time.ticks_ms()
print("[SETUP] flushed %d boot byte(s)" % n)

MQ.put(0x01)
print("[SETUP] TX FIFO pre-loaded with 0x01 (first iter status)")


# ============================================================================
# Per-iteration capture state
# ============================================================================

# Reusable per-iteration buffer (12 bytes: 10 pre-header + 1 ack + 1 crc)
CAP = 16
rx_buf = bytearray(CAP)
rx_t   = [0] * CAP

# Pre-allocated for streaming (read TAP into chunks, push to TX)
prefix     = bytearray(3)
content_el = bytearray(1)

# Cross-iteration state
offset    = 0
iteration = 0
all_iters = []   # snapshots of completed iterations


# ============================================================================
# Capture + respond loop
# ============================================================================

print("=" * 60)
print('READY. Power on TS-2068, then LOAD "".')
print("Pico will send header AND data blocks. TS-2068 should fully LOAD.")
print("Ctrl-C in Thonny when done (or after error settles).")
print("=" * 60)

T0 = time.ticks_us()
rx_count = 0
phase    = "wait_pre"   # wait_pre -> sending -> wait_echo -> done_iter

# Snapshot of "current iter" details (set when we transition wait_pre->sending)
cur_offset    = 0
cur_blk_len   = 0
cur_blk_type  = 0
cur_crc_file  = 0

mq_rx_fifo = MQ.rx_fifo
mq_get     = MQ.get
mq_put     = MQ.put
mq_tx_fifo = MQ.tx_fifo
ticks_us   = time.ticks_us
ticks_diff = time.ticks_diff

gc.collect()

try:
    while True:
        if mq_rx_fifo() > 0:
            raw = mq_get()
            t = ticks_diff(ticks_us(), T0)
            if rx_count < CAP:
                rx_buf[rx_count] = raw & 0xFF
                rx_t[rx_count]   = t
                rx_count += 1

                # ---- Phase transition: pre-header captured ----
                if rx_count == 10 and phase == "wait_pre":
                    phase = "sending"

                    # If the Z80 is asking for a HEADER block (pre[0]==0x00),
                    # rewind to the start of the TAP file. This is what makes
                    # repeated LOAD / VERIFY commands work — each one starts
                    # a fresh LOAD-style sequence and expects the header at
                    # the start of the tape.
                    # If the Z80 is asking for a DATA block (pre[0]==0xFF),
                    # we keep the current offset (it points at the data block
                    # right after the header we just sent).
                    if rx_buf[0] == 0x00:
                        offset = 0

                    # Read TAP block prefix at current offset
                    arch.seek(offset)
                    arch.readinto(prefix)
                    cur_offset    = offset
                    cur_blk_len   = prefix[0] + 256 * prefix[1]
                    cur_blk_type  = prefix[2]

                    # Stream block_type + (blk_len-1) content+CRC bytes.
                    # We allocate the content buffer here to save its CRC
                    # for verification later. For very large blocks (data),
                    # consider streaming byte-by-byte instead.
                    if cur_blk_len <= 256:
                        # Small block — buffer it for CRC verify later
                        content_buf = bytearray(cur_blk_len - 1)
                        arch.readinto(content_buf)
                        cur_crc_file = content_buf[-1]
                        mq_put(cur_blk_type)
                        for b in content_buf:
                            mq_put(b)
                    else:
                        # Large block — stream byte-by-byte (no buffering)
                        cur_crc_file = 0   # we won't track for large blocks
                        mq_put(cur_blk_type)
                        n_stream = cur_blk_len - 1
                        last_byte = 0
                        for _ in range(n_stream):
                            arch.readinto(content_el)
                            last_byte = content_el[0]
                            mq_put(last_byte)
                        cur_crc_file = last_byte   # last byte read = file CRC

                    phase = "wait_echo"

                # ---- Phase transition: echo received ----
                elif rx_count == 12 and phase == "wait_echo":
                    # Send final status + pre-load for next iter
                    mq_put(0x01)   # this iter's final status
                    mq_put(0x01)   # next iter's status pre-load

                    # Snapshot iteration
                    iteration += 1
                    all_iters.append({
                        "iter": iteration,
                        "offset": cur_offset,
                        "blk_len": cur_blk_len,
                        "blk_type": cur_blk_type,
                        "crc_expected": cur_crc_file,
                        "rx": bytes(rx_buf[:rx_count]),
                        "rx_t": list(rx_t[:rx_count]),
                    })

                    # Advance offset for next block in TAP
                    offset += cur_blk_len + 2

                    # Reset for next iter
                    rx_count = 0
                    phase = "wait_pre"

                    # Cleanup heap before next iter
                    gc.collect()

except KeyboardInterrupt:
    pass


# ============================================================================
# Dump all iterations
# ============================================================================

print("")
print("=" * 60)
print("Iterations completed: %d" % len(all_iters))
if rx_count > 0:
    print("Partial iteration in progress at exit: rx_count=%d phase=%s" % (
        rx_count, phase))
print("=" * 60)

pre_labels = ["BLOCK_TYPE","TADDR","BANK","SESS_LO","SESS_HI",
              "MADDR_LO","MADDR_HI","BLEN_LO","BLEN_HI","CRC_TIMEX"]

def dump_iter(log):
    print("\n--- Iteration %d ---" % log["iter"])
    print("offset=%d blk_len=%d blk_type=0x%02X (file CRC=0x%02X)" % (
        log["offset"], log["blk_len"], log["blk_type"], log["crc_expected"]))
    print("RX captured: %d byte(s)" % len(log["rx"]))
    rx = log["rx"]; rx_t = log["rx_t"]
    prev_t = 0
    for i in range(len(rx)):
        t = rx_t[i]; delta = t - prev_t; prev_t = t
        v = rx[i]
        asc = "'%s'" % chr(v) if 0x20 <= v < 0x7F else "   "
        if i < 10:
            lbl = pre_labels[i]
        elif i == 10:
            lbl = "block_type ack (expect 0x%02X)  %s" % (
                rx[0], "MATCH" if v == rx[0] else "DIFFERS")
        elif i == 11:
            lbl = "Z80 computed CRC (expect 0x%02X)  %s" % (
                log["crc_expected"],
                "MATCH" if v == log["crc_expected"] else "DIFFERS")
        else:
            lbl = "(extra)"
        print("  [%2d]  %8d  +%6d  0x%02X  %3s  %s" % (
            i, t, delta, v, asc, lbl))
    # CRC verifications
    if len(rx) >= 10:
        crc = 0
        for i in range(9): crc ^= rx[i]
        print("  Pre-header CRC: computed=0x%02X byte9=0x%02X  %s" % (
            crc, rx[9], "MATCH" if crc == rx[9] else "MISMATCH"))

for log in all_iters:
    dump_iter(log)

# Partial in-flight log
if rx_count > 0:
    partial = {
        "iter": len(all_iters) + 1,
        "offset": cur_offset,
        "blk_len": cur_blk_len,
        "blk_type": cur_blk_type,
        "crc_expected": cur_crc_file,
        "rx": bytes(rx_buf[:rx_count]),
        "rx_t": list(rx_t[:rx_count]),
    }
    print("\n--- PARTIAL Iteration %d (incomplete) ---" % partial["iter"])
    dump_iter(partial)

print("=" * 60)
arch.close()
MQ.active(0)
print("MQ deactivated. ROM_SM/BANK_SM left running.")
