"""Protocol observer V7 — full LOAD + VERIFY (rewinds on header request).

Same as V6 but with one tweak: when the Z80 issues a pre-header asking
for a HEADER block (pre[0] == 0x00), reset the TAP file offset to 0.
This makes back-to-back LOAD/VERIFY commands work — VERIFY starts a new
LOAD-like sequence from the top of the TAP, not from where the last
LOAD left off.

Tests this enables:
  1. LOAD "" — V7 sends header (offset 0) then data (offset 21)
  2. VERIFY "" — pre[0]=0x00 again → V7 rewinds to offset 0,
                 sends same header + data again. Z80 compares against
                 the program already in memory from step 1. Should
                 succeed silently or report 0 OK.
  3. Multiple LOADs / VERIFYs in a row all work.

Note: VERIFY uses TADDR=0x02 (vs LOAD's TADDR=0x01) in pre[1]. From the
Pico's side, both look identical — Pico just streams the TAP block. The
Z80 ROM does the comparison in memory.
"""

import os
import time
import gc
from rp2 import StateMachine, asm_pio, PIO
from machine import Pin, SPI, freq

freq(270_000_000)

from TS.tspico_io import TS_IO_DUAL, set_ctrl, sel_bank
from TS.sdcard import SDCard


# ============================================================================
# Pins + ROM_SM/BANK_SM
# ============================================================================

print("=" * 60)
print("PROTOCOL OBSERVER V6 — full LVM LOAD (header + data)")
print("=" * 60)

U6_EN   = Pin(12, Pin.OUT, Pin.PULL_UP)
WAIT    = Pin(14, Pin.OUT, Pin.PULL_DOWN)
U10_ENA = Pin(19, Pin.OUT, Pin.PULL_UP)
U13_ENA = Pin(20, Pin.OUT, Pin.PULL_UP)
BE      = Pin(21, Pin.OUT, Pin.PULL_UP)
ROSCS   = Pin(26, Pin.IN,  Pin.PULL_DOWN)
U10_WE  = Pin(27, Pin.OUT, Pin.PULL_UP)
for p in (U6_EN, WAIT, U10_ENA, U13_ENA, BE, U10_WE):
    p.value(1)

rom_sm = StateMachine(4, set_ctrl, freq=150_000_000,
                      in_base=Pin(0, Pin.IN), jmp_pin=Pin(26),
                      set_base=Pin(21, Pin.OUT),
                      out_base=Pin(19, Pin.OUT))
rom_sm.active(1)
bank_sm = StateMachine(5, sel_bank, freq=150_000_000,
                       jmp_pin=Pin(26),
                       out_base=Pin(15, Pin.OUT))
bank_sm.active(1)
rom_sm.put(0x0A)
bank_sm.put(0x01)
print("[SETUP] ROM_SM/BANK_SM running")


# ============================================================================
# SD mount + copy
# ============================================================================

@asm_pio(autopull=True, pull_thresh=8)
def NULL_SM():
    nop()

# Small test file: "10 PRINT \"test\" / 20 GO TO 10". Generated by
# test/make_test_tap.py — copy onto the SD card as /TAP/test.tap. NO
# autorun, so the program sits at BASIC ready prompt after LOAD,
# making it safe for VERIFY testing (memory state is preserved).
SD_TAP_PATH = "/sd/TAP/test.tap"
LOCAL_TAP   = "/TMP/temp.tap"

print("[SETUP] mounting SD")
null = StateMachine(0, NULL_SM, freq=15_000_000)
null.active(1); null.active(0)
U3_CS = Pin(28, Pin.OUT, Pin.PULL_UP)
D0 = Pin(2, Pin.IN); D1 = Pin(3, Pin.IN); D2 = Pin(4, Pin.IN)
spi = SPI(0, sck=D0, mosi=D1, miso=D2)
sd = SDCard(spi, U3_CS)
os.mount(sd, "/sd")

try: os.mkdir("/TMP")
except OSError: pass

src_size = os.stat(SD_TAP_PATH)[6]
print("[SETUP] copying %s (%d bytes) -> %s" % (SD_TAP_PATH, src_size, LOCAL_TAP))
with open(SD_TAP_PATH, "rb") as src, open(LOCAL_TAP, "wb") as dst:
    while True:
        buf = src.read(512)
        if not buf:
            break
        dst.write(buf)
print("[SETUP] copy done")

os.umount("/sd")
spi.deinit()
Pin(28, Pin.OUT, Pin.PULL_UP).value(1)
for p in (2, 3, 4):
    Pin(p, Pin.OUT).value(0)


# ============================================================================
# Pre-open TAP file (we'll read each block lazily as Z80 requests it)
# ============================================================================

arch = open(LOCAL_TAP, "rb")
print("[SETUP] pre-opened %s" % LOCAL_TAP)


# ============================================================================
# Start MQ + pre-load status
# ============================================================================

MQ = StateMachine(0, TS_IO_DUAL, freq=30_000_000,
                  out_base=Pin(2, Pin.OUT),
                  in_base=Pin(2, Pin.IN),
                  jmp_pin=Pin(11),
                  sideset_base=Pin(12, Pin.OUT))
MQ.active(1)
MQ.exec("mov(y, invert(null))")
print("[SETUP] MQ active, Y=READY")

n = 0
last = time.ticks_ms()
while time.ticks_diff(time.ticks_ms(), last) < 300:
    if MQ.rx_fifo() > 0:
        MQ.get()
        n += 1
        last = time.ticks_ms()
print("[SETUP] flushed %d boot byte(s)" % n)

MQ.put(0x01)
print("[SETUP] TX FIFO pre-loaded with 0x01 (first iter status)")


# ============================================================================
# Per-iteration capture state
# ============================================================================

# Reusable per-iteration buffer (12 bytes: 10 pre-header + 1 ack + 1 crc)
CAP = 16
rx_buf = bytearray(CAP)
rx_t   = [0] * CAP

# Pre-allocated for streaming (read TAP into chunks, push to TX)
prefix     = bytearray(3)
content_el = bytearray(1)

# Cross-iteration state
offset    = 0
iteration = 0
all_iters = []   # snapshots of completed iterations


# ============================================================================
# Capture + respond loop
# ============================================================================

print("=" * 60)
print('READY. Power on TS-2068, then LOAD "".')
print("Pico will send header AND data blocks. TS-2068 should fully LOAD.")
print("Ctrl-C in Thonny when done (or after error settles).")
print("=" * 60)

T0 = time.ticks_us()
rx_count = 0
phase    = "wait_pre"   # wait_pre -> sending -> wait_echo -> done_iter

# Snapshot of "current iter" details (set when we transition wait_pre->sending)
cur_offset    = 0
cur_blk_len   = 0
cur_blk_type  = 0
cur_crc_file  = 0

mq_rx_fifo = MQ.rx_fifo
mq_get     = MQ.get
mq_put     = MQ.put
mq_tx_fifo = MQ.tx_fifo
ticks_us   = time.ticks_us
ticks_diff = time.ticks_diff

gc.collect()

try:
    while True:
        if mq_rx_fifo() > 0:
            raw = mq_get()
            t = ticks_diff(ticks_us(), T0)
            if rx_count < CAP:
                rx_buf[rx_count] = raw & 0xFF
                rx_t[rx_count]   = t
                rx_count += 1

                # ---- Phase transition: pre-header captured ----
                if rx_count == 10 and phase == "wait_pre":
                    phase = "sending"

                    # If the Z80 is asking for a HEADER block (pre[0]==0x00),
                    # rewind to the start of the TAP file. This is what makes
                    # repeated LOAD / VERIFY commands work — each one starts
                    # a fresh LOAD-style sequence and expects the header at
                    # the start of the tape.
                    # If the Z80 is asking for a DATA block (pre[0]==0xFF),
                    # we keep the current offset (it points at the data block
                    # right after the header we just sent).
                    if rx_buf[0] == 0x00:
                        offset = 0

                    # Read TAP block prefix at current offset
                    arch.seek(offset)
                    arch.readinto(prefix)
                    cur_offset    = offset
                    cur_blk_len   = prefix[0] + 256 * prefix[1]
                    cur_blk_type  = prefix[2]

                    # Stream block_type + (blk_len-1) content+CRC bytes.
                    # We allocate the content buffer here to save its CRC
                    # for verification later. For very large blocks (data),
                    # consider streaming byte-by-byte instead.
                    if cur_blk_len <= 256:
                        # Small block — buffer it for CRC verify later
                        content_buf = bytearray(cur_blk_len - 1)
                        arch.readinto(content_buf)
                        cur_crc_file = content_buf[-1]
                        mq_put(cur_blk_type)
                        for b in content_buf:
                            mq_put(b)
                    else:
                        # Large block — stream byte-by-byte (no buffering)
                        cur_crc_file = 0   # we won't track for large blocks
                        mq_put(cur_blk_type)
                        n_stream = cur_blk_len - 1
                        last_byte = 0
                        for _ in range(n_stream):
                            arch.readinto(content_el)
                            last_byte = content_el[0]
                            mq_put(last_byte)
                        cur_crc_file = last_byte   # last byte read = file CRC

                    phase = "wait_echo"

                # ---- Phase transition: echo received ----
                elif rx_count == 12 and phase == "wait_echo":
                    # Send final status + pre-load for next iter
                    mq_put(0x01)   # this iter's final status
                    mq_put(0x01)   # next iter's status pre-load

                    # Snapshot iteration
                    iteration += 1
                    all_iters.append({
                        "iter": iteration,
                        "offset": cur_offset,
                        "blk_len": cur_blk_len,
                        "blk_type": cur_blk_type,
                        "crc_expected": cur_crc_file,
                        "rx": bytes(rx_buf[:rx_count]),
                        "rx_t": list(rx_t[:rx_count]),
                    })

                    # Advance offset for next block in TAP
                    offset += cur_blk_len + 2

                    # Reset for next iter
                    rx_count = 0
                    phase = "wait_pre"

                    # Cleanup heap before next iter
                    gc.collect()

except KeyboardInterrupt:
    pass


# ============================================================================
# Dump all iterations
# ============================================================================

print("")
print("=" * 60)
print("Iterations completed: %d" % len(all_iters))
if rx_count > 0:
    print("Partial iteration in progress at exit: rx_count=%d phase=%s" % (
        rx_count, phase))
print("=" * 60)

pre_labels = ["BLOCK_TYPE","TADDR","BANK","SESS_LO","SESS_HI",
              "MADDR_LO","MADDR_HI","BLEN_LO","BLEN_HI","CRC_TIMEX"]

def dump_iter(log):
    print("\n--- Iteration %d ---" % log["iter"])
    print("offset=%d blk_len=%d blk_type=0x%02X (file CRC=0x%02X)" % (
        log["offset"], log["blk_len"], log["blk_type"], log["crc_expected"]))
    print("RX captured: %d byte(s)" % len(log["rx"]))
    rx = log["rx"]; rx_t = log["rx_t"]
    prev_t = 0
    for i in range(len(rx)):
        t = rx_t[i]; delta = t - prev_t; prev_t = t
        v = rx[i]
        asc = "'%s'" % chr(v) if 0x20 <= v < 0x7F else "   "
        if i < 10:
            lbl = pre_labels[i]
        elif i == 10:
            lbl = "block_type ack (expect 0x%02X)  %s" % (
                rx[0], "MATCH" if v == rx[0] else "DIFFERS")
        elif i == 11:
            lbl = "Z80 computed CRC (expect 0x%02X)  %s" % (
                log["crc_expected"],
                "MATCH" if v == log["crc_expected"] else "DIFFERS")
        else:
            lbl = "(extra)"
        print("  [%2d]  %8d  +%6d  0x%02X  %3s  %s" % (
            i, t, delta, v, asc, lbl))
    # CRC verifications
    if len(rx) >= 10:
        crc = 0
        for i in range(9): crc ^= rx[i]
        print("  Pre-header CRC: computed=0x%02X byte9=0x%02X  %s" % (
            crc, rx[9], "MATCH" if crc == rx[9] else "MISMATCH"))

for log in all_iters:
    dump_iter(log)

# Partial in-flight log
if rx_count > 0:
    partial = {
        "iter": len(all_iters) + 1,
        "offset": cur_offset,
        "blk_len": cur_blk_len,
        "blk_type": cur_blk_type,
        "crc_expected": cur_crc_file,
        "rx": bytes(rx_buf[:rx_count]),
        "rx_t": list(rx_t[:rx_count]),
    }
    print("\n--- PARTIAL Iteration %d (incomplete) ---" % partial["iter"])
    dump_iter(partial)

print("=" * 60)
arch.close()
MQ.active(0)
print("MQ deactivated. ROM_SM/BANK_SM left running.")
