#!/usr/bin/env bash
#
# Assemble one updater payload ("channel"): the Pico-flash files from SRC_DIR,
# the firmware and upgrade UF2s, the SD-card bundle, and a manifest.json
# describing them. pages.yml builds two channels next to the page --
# release/ (the latest GitHub Release) and main/ (the latest green build of
# main, for testers) -- and the page fetches everything from them
# same-origin (GitHub's release-asset CDN blocks browser CORS; see README).
#
# Usage:
#   ./build-payload.sh [SRC_DIR] [TAG] [UF2_PATH]
#
#   SRC_DIR   firmware source dir (default: ../src)
#   TAG       label for the manifest: a release tag, or main@<sha> (default: dev-local)
#   UF2_PATH  firmware.uf2 to include (optional)
#
# Optional environment:
#   OUT_DIR      where to write the channel (default: web-updater/release)
#   CHANNEL      "release" or "main" (default: release)
#   UPGRADE_UF2  the upgrade UF2 (src/upgrade/) for boards coming from 1.1/1.5
#   SDCARD_DIR   the SD-card folder to zip (default: SRC_DIR/../SD card)
#   SOURCE_URL   a link the page shows for where this build came from
#
# Output (gitignored): OUT_DIR/{manifest.json, pico/, firmware.uf2,
# firmware-uf2.zip, upgrade.uf2, sdcard.zip}
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="${1:-$HERE/../src}"
SRC="$(cd "$SRC" && pwd)"
TAG="${2:-dev-local}"
UF2="${3:-}"
OUT="${OUT_DIR:-$HERE/release}"
CHANNEL="${CHANNEL:-release}"
UPGRADE_UF2="${UPGRADE_UF2:-}"
SDCARD_SRC="${SDCARD_DIR:-$(cd "$SRC/.." && pwd)/SD card}"
SOURCE_URL="${SOURCE_URL:-}"

rm -rf "$OUT"
mkdir -p "$OUT/pico/assets"
OUT="$(cd "$OUT" && pwd)"

# Pico-flash filesystem content: what the UF2 doesn't carry. The UF2 freezes
# the TS/ package (src/manifest.py); main.py, config.ini, words.txt and the
# assets live on the Pico's LittleFS and are written over the serial REPL.
#
# help/ is deliberately NOT included: the BASIC help text lives on the SD card
# (SD card/help/), read by the firmware from /help/ on the mounted card.
cp "$SRC/main.py"      "$OUT/pico/main.py"
cp "$SRC/config.ini"   "$OUT/pico/config.ini"
cp "$SRC/words.txt"    "$OUT/pico/words.txt"
cp "$SRC"/assets/*.tap "$OUT/pico/assets/"

# The firmware needs these three on the Pico's flash (bare LOAD "" with nothing
# mounted, and mounting a .ROM or .DCK). They are generated by
# tools/build-basic.sh, not committed, so refuse a payload built from a tree
# where nobody ran it -- a board installed from it silently lacks them.
for t in nofile romupdate dckupdate; do
  if [ ! -f "$OUT/pico/assets/$t.tap" ]; then
    echo "build-payload: $SRC/assets/$t.tap is missing -- run tools/build-basic.sh on that tree first" >&2
    exit 1
  fi
done

# The firmware UF2 -- written through the bootloader, not the REPL. Also
# offered zipped for the manual path: some Windows antivirus/SmartScreen
# setups block or quarantine a raw .uf2 download.
UF2_FIELD="null"
UF2_ZIP_FIELD="null"
if [ -n "$UF2" ] && [ -f "$UF2" ]; then
  cp "$UF2" "$OUT/firmware.uf2"
  UF2_FIELD='"firmware.uf2"'
  ( cd "$OUT" && zip -q firmware-uf2.zip firmware.uf2 )
  UF2_ZIP_FIELD='"firmware-uf2.zip"'
  echo "Included firmware.uf2 (+ firmware-uf2.zip)"
else
  echo "No firmware UF2 -- the page will offer only the file upload for this channel"
fi

# The upgrade UF2 (src/upgrade/): a separate firmware that serves the ROM
# updater tape to a 2068 whose ROM predates 2.0. The page writes it between
# the wipe and the real firmware when the user is coming from 1.1/1.5.
UPGRADE_FIELD="null"
if [ -n "$UPGRADE_UF2" ] && [ -f "$UPGRADE_UF2" ]; then
  cp "$UPGRADE_UF2" "$OUT/upgrade.uf2"
  UPGRADE_FIELD='"upgrade.uf2"'
  echo "Included upgrade.uf2"
else
  echo "No upgrade UF2 -- the ROM update step is unavailable for this channel"
fi

# SD card bundle (software testers only): a plain download, with its contents
# (TAP/, help/) at the zip root so "unzip -> copy to card root" is a direct drag.
SDCARD_FIELD="null"
if [ -d "$SDCARD_SRC" ]; then
  TMP="$(mktemp -d)"
  cp -R "$SDCARD_SRC/." "$TMP/"
  find "$TMP" -name '.DS_Store' -delete
  ( cd "$TMP" && zip -rq "$OUT/sdcard.zip" . )
  rm -rf "$TMP"
  SDCARD_BYTES="$(wc -c < "$OUT/sdcard.zip" | tr -d ' ')"
  SDCARD_NFILES="$(find "$SDCARD_SRC" -type f ! -name '.DS_Store' | wc -l | tr -d ' ')"
  SDCARD_FIELD="{\"path\": \"sdcard.zip\", \"size\": ${SDCARD_BYTES}, \"files\": ${SDCARD_NFILES}}"
  echo "Included sdcard.zip (${SDCARD_NFILES} files, ${SDCARD_BYTES} bytes)"
else
  echo "No SD card dir at $SDCARD_SRC -- skipping sdcard.zip"
fi

# manifest.json. File paths are relative to pico/; UF2 and zip paths to the
# channel directory. Versions come from config.ini, which carries both.
python3 - "$OUT" "$TAG" "$CHANNEL" "$SOURCE_URL" "$UF2_FIELD" "$UF2_ZIP_FIELD" \
          "$UPGRADE_FIELD" "$SDCARD_FIELD" > "$OUT/manifest.json" <<'PY'
import json, os, sys
out, tag, channel, source_url, uf2, uf2_zip, upgrade, sdcard = sys.argv[1:9]
cfg = json.load(open(os.path.join(out, 'pico', 'config.ini')))
opt = lambda v: None if v == 'null' else json.loads(v)
files = []
for root, _dirs, names in os.walk(os.path.join(out, 'pico')):
    for n in sorted(names):
        full = os.path.join(root, n)
        rel = os.path.relpath(full, os.path.join(out, 'pico')).replace(os.sep, '/')
        files.append({'path': rel, 'size': os.path.getsize(full)})
files.sort(key=lambda f: f['path'])
print(json.dumps({
    'channel': channel,
    'tag': tag,
    'source_url': source_url or None,
    'fw_version': cfg.get('FW_VERSION', '?'),
    'rom_version': cfg.get('ROM_VERSION'),
    'uf2': opt(uf2),
    'uf2_zip': opt(uf2_zip),
    'upgrade_uf2': opt(upgrade),
    'sdcard': opt(sdcard),
    'files': files,
}, indent=2))
PY

echo "Wrote $OUT ($(find "$OUT/pico" -type f | wc -l | tr -d ' ') Pico files)"
echo "Channel: $CHANNEL  Tag: $TAG  Firmware: $(python3 -c "import json;print(json.load(open('$OUT/manifest.json'))['fw_version'])")"
