#!/usr/bin/env bash
#
# Assemble one updater payload ("channel"): the Pico-flash files from SRC_DIR,
# the firmware and upgrade UF2s, the SD-card bundle, and a manifest.json
# describing them. pages.yml builds two channels next to the page --
# release/ (the latest GitHub Release) and main/ (the latest green build of
# main, for testers) -- and the page fetches everything from them
# same-origin (GitHub's release-asset CDN blocks browser CORS; see README).
#
# Usage:
#   ./build-payload.sh [SRC_DIR] [TAG] [UF2_PATH]
#
#   SRC_DIR   firmware source dir (default: ../src)
#   TAG       label for the manifest: a release tag, or main@<sha> (default: dev-local)
#   UF2_PATH  firmware.uf2 to include (optional)
#
# Optional environment:
#   OUT_DIR      where to write the channel (default: web-updater/release)
#   CHANNEL      "release" or "main" (default: release)
#   UPGRADE_UF2  the upgrade UF2 (src/upgrade/) for boards coming from 1.1/1.5
#   SDCARD_DIR   the SD-card folder to zip (default: SRC_DIR/../SD card)
#   SOURCE_URL   a link the page shows for where this build came from
#   V3_UF2       the v3 card's firmware (src/boards/TSPICO_V3), if this channel has one
#   V3_SLOTS     a folder of the v3 card's slot files, F00.bin ... F15.bin
#                (tools/build-flash.py build --slots)
#
# Output (gitignored): OUT_DIR/{manifest.json, pico/, firmware.uf2,
# firmware-uf2.zip, upgrade.uf2, sdcard.zip, firmware-v3.uf2, slots/}
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="${1:-$HERE/../src}"
SRC="$(cd "$SRC" && pwd)"
TAG="${2:-dev-local}"
UF2="${3:-}"
OUT="${OUT_DIR:-$HERE/release}"
CHANNEL="${CHANNEL:-release}"
UPGRADE_UF2="${UPGRADE_UF2:-}"
SDCARD_SRC="${SDCARD_DIR:-$(cd "$SRC/.." && pwd)/SD card}"
SOURCE_URL="${SOURCE_URL:-}"
V3_UF2="${V3_UF2:-}"
V3_SLOTS="${V3_SLOTS:-}"

rm -rf "$OUT"
mkdir -p "$OUT/pico/assets"
OUT="$(cd "$OUT" && pwd)"

# Pico-flash filesystem content: what the UF2 doesn't carry. The UF2 freezes
# the TS/ package (src/manifest.py); main.py, config.ini, words.txt and the
# assets live on the Pico's LittleFS and are written over the serial REPL.
#
# help/ is deliberately NOT included: the BASIC help text lives on the SD card
# (SD card/help/), read by the firmware from /help/ on the mounted card.
cp "$SRC/main.py"      "$OUT/pico/main.py"
cp "$SRC/config.ini"   "$OUT/pico/config.ini"
cp "$SRC/words.txt"    "$OUT/pico/words.txt"
cp "$SRC"/assets/*.tap "$OUT/pico/assets/"

# The firmware needs these three on the Pico's flash (bare LOAD "" with nothing
# mounted, and mounting a .ROM or .DCK). They are generated by
# tools/build-basic.sh, not committed, so refuse a payload built from a tree
# where nobody ran it -- a board installed from it silently lacks them.
for t in nofile romupdate dckupdate; do
  if [ ! -f "$OUT/pico/assets/$t.tap" ]; then
    echo "build-payload: $SRC/assets/$t.tap is missing -- run tools/build-basic.sh on that tree first" >&2
    exit 1
  fi
done

# The firmware UF2 -- written through the bootloader, not the REPL. Also
# offered zipped for the manual path: some Windows antivirus/SmartScreen
# setups block or quarantine a raw .uf2 download.
UF2_FIELD="null"
UF2_ZIP_FIELD="null"
if [ -n "$UF2" ] && [ -f "$UF2" ]; then
  cp "$UF2" "$OUT/firmware.uf2"
  UF2_FIELD='"firmware.uf2"'
  ( cd "$OUT" && zip -q firmware-uf2.zip firmware.uf2 )
  UF2_ZIP_FIELD='"firmware-uf2.zip"'
  echo "Included firmware.uf2 (+ firmware-uf2.zip)"
else
  echo "No firmware UF2 -- the page will offer only the file upload for this channel"
fi

# The upgrade UF2 (src/upgrade/): a separate firmware that serves the ROM
# updater tape to a 2068 whose ROM predates 2.0. The page writes it between
# the wipe and the real firmware when the user is coming from 1.1/1.5.
UPGRADE_FIELD="null"
if [ -n "$UPGRADE_UF2" ] && [ -f "$UPGRADE_UF2" ]; then
  cp "$UPGRADE_UF2" "$OUT/upgrade.uf2"
  UPGRADE_FIELD='"upgrade.uf2"'
  echo "Included upgrade.uf2"
else
  echo "No upgrade UF2 -- the ROM update step is unavailable for this channel"
fi

# The v3 card (RP2350B): its own firmware, and the slot files that hold its
# ROMs and cartridges (it has no flash chip; docs/v3-slots-proposal.md). The
# page writes the firmware through the bootloader and the slot files over the
# REPL into /slots. Slots 0 and 1 (our Spectrum and TS-Pico ROMs) are always
# written; the others only where the card has no such file, so a user's own
# ROM in a slot is never overwritten. It never wipes a v3 card: the slots
# live on the same flash as the firmware.
V3_FIELD="null"
if [ -n "$V3_UF2" ] && [ -f "$V3_UF2" ]; then
  cp "$V3_UF2" "$OUT/firmware-v3.uf2"
  mkdir -p "$OUT/slots"
  if [ -n "$V3_SLOTS" ] && [ -d "$V3_SLOTS" ]; then
    find "$V3_SLOTS" -maxdepth 1 -name 'F[0-9][0-9].bin' -exec cp {} "$OUT/slots/" \;
  fi
  for t in romupd3 dckupd3; do
    if [ ! -f "$OUT/pico/assets/$t.tap" ]; then
      echo "build-payload: $SRC/assets/$t.tap is missing -- the v3 card needs it; run tools/build-basic.sh" >&2
      exit 1
    fi
  done
  V3_FIELD='"firmware-v3.uf2"'
  echo "Included firmware-v3.uf2 and $(find "$OUT/slots" -name '*.bin' | wc -l | tr -d ' ') slot file(s)"
else
  echo "No v3 firmware -- the page will say this channel has nothing for the v3 card"
fi

# SD card bundle (software testers only): a plain download, with its contents
# (TAP/, help/) at the zip root so "unzip -> copy to card root" is a direct drag.
SDCARD_FIELD="null"
if [ -d "$SDCARD_SRC" ]; then
  TMP="$(mktemp -d)"
  cp -R "$SDCARD_SRC/." "$TMP/"
  find "$TMP" -name '.DS_Store' -delete
  ( cd "$TMP" && zip -rq "$OUT/sdcard.zip" . )
  rm -rf "$TMP"
  SDCARD_BYTES="$(wc -c < "$OUT/sdcard.zip" | tr -d ' ')"
  SDCARD_NFILES="$(find "$SDCARD_SRC" -type f ! -name '.DS_Store' | wc -l | tr -d ' ')"
  SDCARD_FIELD="{\"path\": \"sdcard.zip\", \"size\": ${SDCARD_BYTES}, \"files\": ${SDCARD_NFILES}}"
  echo "Included sdcard.zip (${SDCARD_NFILES} files, ${SDCARD_BYTES} bytes)"
else
  echo "No SD card dir at $SDCARD_SRC -- skipping sdcard.zip"
fi

# manifest.json. File paths are relative to pico/; UF2 and zip paths to the
# channel directory. Versions come from config.ini, which carries both.
python3 - "$OUT" "$TAG" "$CHANNEL" "$SOURCE_URL" "$UF2_FIELD" "$UF2_ZIP_FIELD" \
          "$UPGRADE_FIELD" "$SDCARD_FIELD" "$V3_FIELD" > "$OUT/manifest.json" <<'PY'
import json, os, sys
out, tag, channel, source_url, uf2, uf2_zip, upgrade, sdcard, v3 = sys.argv[1:10]
cfg = json.load(open(os.path.join(out, 'pico', 'config.ini')))
opt = lambda v: None if v == 'null' else json.loads(v)


def mp_version(name='firmware.uf2'):
    """The MicroPython release in a firmware UF2 ("1.29.0"), or None. The
    page warns before installing an older one over a newer: a newer
    MicroPython's filesystem can't be read by an older one, which then
    formats the Pico's flash on its first boot."""
    import re
    try:
        d = open(os.path.join(out, name), 'rb').read()
    except OSError:
        return None
    pay = b''.join(d[i + 32:i + 32 + 256] for i in range(0, len(d), 512))
    m = re.search(rb'MicroPython v(\d+\.\d+\.\d+)', pay)
    return m.group(1).decode() if m else None
files = []
for root, _dirs, names in os.walk(os.path.join(out, 'pico')):
    for n in sorted(names):
        full = os.path.join(root, n)
        rel = os.path.relpath(full, os.path.join(out, 'pico')).replace(os.sep, '/')
        files.append({'path': rel, 'size': os.path.getsize(full)})
files.sort(key=lambda f: f['path'])
v3_info = None
if opt(v3):
    slots = []
    for n in sorted(os.listdir(os.path.join(out, 'slots'))):
        if n.endswith('.bin'):
            k = int(n[1:3])
            slots.append({'file': 'slots/' + n, 'path': 'slots/' + n, 'slot': k,
                          'size': os.path.getsize(os.path.join(out, 'slots', n)),
                          'always': k in (0, 1)})   # ours: rewritten every time; others only if missing
    v3_info = {'uf2': opt(v3), 'mp_version': mp_version(opt(v3)), 'slots': slots}
print(json.dumps({
    'channel': channel,
    'tag': tag,
    'source_url': source_url or None,
    'fw_version': cfg.get('FW_VERSION', '?'),
    'mp_version': mp_version(),
    'rom_version': cfg.get('ROM_VERSION'),
    'uf2': opt(uf2),
    'uf2_zip': opt(uf2_zip),
    'upgrade_uf2': opt(upgrade),
    'sdcard': opt(sdcard),
    'files': files,
    'v3': v3_info,
}, indent=2))
PY

echo "Wrote $OUT ($(find "$OUT/pico" -type f | wc -l | tr -d ' ') Pico files)"
echo "Channel: $CHANNEL  Tag: $TAG  Firmware: $(python3 -c "import json;print(json.load(open('$OUT/manifest.json'))['fw_version'])")"
