/*
 * tsbus: the TS-Pico v3 card's bus, as a MicroPython module (phase 3 of the v3
 * port plan, docs/v3-firmware-port-plan.md in the tspico-hardware repo).
 *
 * The card has no memory chips: it answers every 2068 memory read it owns
 * from images in SRAM, and the TS-Pico ports 0Eh/0Fh from core 1. This is the
 * phase 1 bus test (firmware/bringup/bus_card.c in tspico-hardware), moved
 * under MicroPython:
 *
 * - PIO0: serve (reads the address off MD, decides through a chunk table,
 *   asserts /BE, pushes a pointer, drives the byte) and io_drive (replies to
 *   IN 0Eh/0Fh). PIO1: addr_read (the address-buffer enables), mem_write
 *   (every memory write) and io_snoop (every I/O write). Both are full.
 * - DMA: ch_ptr takes serve's pointer and triggers ch_data, which copies the
 *   byte into serve's TX FIFO and chains to ch_log, which logs the pointer.
 * - Core 1 runs only this code, from SRAM, with its own vector table: the bank
 *   shadow (ports F4h, FFh) and the chunk table, DOCK writes, the IN handler
 *   on /IORD, and OUTs to 0Eh/0Fh.
 * - Images at TSBUS_IMAGE_REGION (the top 256 KB of SRAM, outside the GC heap;
 *   src/boards/TSPICO_V3/memmap): the byte for (address, slot) is at
 *   IMAGE_REGION + 4 * address + slot. Slots: 0 HOME, 1 EXROM, 2 DOCK.
 *
 * Python API (this step; slots and the MQ object come next):
 *   tsbus.start()                  250 MHz; claim PIO0, PIO1 and 3 DMA channels;
 *                                  start core 1
 *   tsbus.load(slot, data)         copy data into a slot, repeated to fill 64 KB
 *   tsbus.serve(on)                /BE and U3 live (the 2068 must be held)
 *   tsbus.exrom(on), tsbus.dock(on) serve the EXROM / DOCK banks' chunks
 *   tsbus.hold(on)                 hold the 2068 in reset, or release it
 *   tsbus.stats()                  counters, as a dict
 *
 * Nothing on core 1 may touch flash: LittleFS writes stop execute-in-place,
 * and core 1 is never paused for them (it is not a multicore lockout victim).
 * Its code is __not_in_flash_func and uses registers directly rather than SDK
 * inline helpers, which a size-optimised build may leave out of line in flash.
 */

#include <string.h>

#include "py/runtime.h"
#include "py/mphal.h"

#include "pico/multicore.h"
#include "hardware/clocks.h"
#include "hardware/dma.h"
#include "hardware/irq.h"
#include "hardware/pio.h"
#include "hardware/structs/busctrl.h"
#include "hardware/structs/io_bank0.h"
#include "hardware/structs/m33.h"
#include "hardware/structs/scb.h"
#include "hardware/structs/sio.h"
#include "hardware/vreg.h"

#include "rp2_flash.h"

#include "tspico_v3_pins.h"
// Generated by pioasm. MicroPython's QSTR scan preprocesses this file (with
// NO_QSTR defined) before the header exists; it needs no PIO names.
#ifndef NO_QSTR
#include "tsbus.pio.h"
#endif

#define TSBUS_IMAGE_REGION 0x20040000u
#define IMAGE_PREFIX (TSBUS_IMAGE_REGION >> 18)
#define IMAGE_SIZE (256 * 1024)
#define SLOT_HOME  0
#define SLOT_EXROM 1
#define SLOT_DOCK  2
#define BUS_CLOCK_HZ 250000000u

extern uint8_t __GcHeapEnd;

static const PIO pio_serve = pio0, pio_addr = pio1;
static uint sm_serve, sm_iodrv, sm_addr, sm_write, sm_snoop, off_addr;
static int ch_ptr, ch_data, ch_log;
static bool started;

// Set by core 0, read by core 1's loop: volatile, or the compiler reads them
// once at the top of the loop.
static volatile bool serving;     // /BE and U3 requests live
static volatile bool exrom_on;    // EXROM-bank chunks served (with /BE)
static volatile bool dock_on;     // DOCK-bank chunks served (no /BE)
static volatile bool held_2068 = true;
static volatile bool core1_ready;

// Timing, in PIO cycles (4 ns at 250 MHz), as phase 1 settled them: serve's
// wait after U2 comes on and before sampling A7..A0, addr_read's U2 and U1
// hold loops (tsbus.pio).
static const uint d_hi = 3, d_lo = 3, hold_hi = 5, hold_lo = 9;

// ---- logs and counters ---------------------------------------------------------

#define LOG_N 4096
static uint32_t addr_log[LOG_N] __attribute__((aligned(LOG_N * 4)));
static uint32_t ring_seen;

static volatile uint8_t sh_hsr, sh_ff;
static volatile uint32_t io_writes, mem_writes, dock_writes, table_updates;
static volatile uint32_t served[3];

// ---- ports 0Eh / 0Fh -------------------------------------------------------------

// Reply queue for IN 0Eh (empty reads 00h), and the status byte IN 0Fh returns.
// Any OUT to 0Eh/0Fh makes the status 00h (busy), as v2.1's PIO did, and goes
// to the receive queue (port 0Fh as 0x100 | data). Nothing reads the queues
// yet; the MQ object comes next.
#define TXQ_N 1024
static volatile uint8_t txq[TXQ_N];
static volatile uint32_t txq_head, txq_tail;     // head: core 0; tail: core 1
#define RXQ_N 1024
static volatile uint16_t rxq[RXQ_N];
static volatile uint32_t rxq_head, rxq_tail;     // head: core 1; tail: core 0
static volatile uint32_t rxq_lost;
static volatile uint8_t io_status = 0xff;

static volatile uint32_t io_ins, io_in_ours, io_outs_ours, io_in_late, respond_max;

// ---- serve's table and patches -----------------------------------------------------

// serve is loaded at offset 0, so its labels are instruction addresses, and a
// table entry is an unconditional jmp: the encoding is just the target.
static uint __not_in_flash_func(chunk_target)(uint chunk, uint hsr, uint ff) {
    if ((hsr >> chunk) & 1) {
        if (ff & 0x80) {
            return exrom_on ? serve_offset_path_e : serve_offset_tail;
        }
        return dock_on ? serve_offset_path_d : serve_offset_tail;
    }
    return chunk < 2 ? serve_offset_path_h : serve_offset_tail;
}

static void __not_in_flash_func(write_table)(void) {
    uint hsr = sh_hsr, ff = sh_ff;
    for (uint c = 0; c < 8; c++) {
        pio_serve->instr_mem[c] = chunk_target(c, hsr, ff);
    }
    table_updates++;
}

// serve has one optional side-set pin, so its instruction word is opt (bit 12),
// side value (bit 11), delay (bits 10:8). Shadow mode drops the /BE side-sets on
// path_e and path_h and turns the U3 request into a nop with the same delay.
#define SIDE_BITS  0x1800u
#define DELAY_BITS 0x0700u
static void set_serving(bool on) {
    serving = on;
    uint16_t e = serve_program_instructions[serve_offset_path_e];
    uint16_t h = serve_program_instructions[serve_offset_path_h];
    pio_serve->instr_mem[serve_offset_path_e] = on ? e : (e & ~SIDE_BITS);
    pio_serve->instr_mem[serve_offset_path_h] = on ? h : (h & ~SIDE_BITS);
    uint16_t req = on ? serve_program_instructions[serve_offset_req] : pio_encode_nop();
    pio_serve->instr_mem[serve_offset_req] = (req & ~DELAY_BITS) | (d_lo << 8);
}

static void set_delays(void) {
    pio_serve->instr_mem[serve_offset_entry] =
        (serve_program_instructions[serve_offset_entry] & ~DELAY_BITS) | (d_hi << 8);
    pio_addr->instr_mem[off_addr + addr_read_offset_hi_hold] = pio_encode_set(pio_y, hold_hi);
    // lo_hold also side-sets U1 on (opt bit and value in bits 12:9 for 3 pins + opt).
    pio_addr->instr_mem[off_addr + addr_read_offset_lo_hold] =
        (addr_read_program_instructions[addr_read_offset_lo_hold] & ~0x1fu) | hold_lo;
}

// ---- start: PIO and DMA ------------------------------------------------------------

static int claim_sm(PIO pio) {
    int sm = pio_claim_unused_sm(pio, false);
    if (sm < 0) {
        mp_raise_msg_varg(&mp_type_OSError, MP_ERROR_TEXT("tsbus: no free state machine in PIO%d"),
            pio_get_index(pio));
    }
    return sm;
}

static uint add_program(PIO pio, const pio_program_t *prog) {
    if (!pio_can_add_program(pio, prog)) {
        mp_raise_msg_varg(&mp_type_OSError, MP_ERROR_TEXT("tsbus: no room in PIO%d"), pio_get_index(pio));
    }
    return pio_add_program(pio, prog);
}

static int claim_dma(void) {
    int ch = dma_claim_unused_channel(false);
    if (ch < 0) {
        mp_raise_msg(&mp_type_OSError, MP_ERROR_TEXT("tsbus: no free DMA channel"));
    }
    return ch;
}

static void bus_start(void) {
    pio_set_gpio_base(pio_serve, 0);
    pio_set_gpio_base(pio_addr, 0);

    // serve (PIO0, offset 0): MD and BE_REQ. MD starts as inputs, /BE off.
    sm_serve = claim_sm(pio_serve);
    if (!pio_can_add_program_at_offset(pio_serve, &serve_program, 0)) {
        mp_raise_msg(&mp_type_OSError, MP_ERROR_TEXT("tsbus: PIO0 offset 0 is in use"));
    }
    pio_add_program_at_offset(pio_serve, &serve_program, 0);
    pio_sm_config c = serve_program_get_default_config(0);
    sm_config_set_in_pin_base(&c, PIN_MD0);
    sm_config_set_out_pins(&c, PIN_MD0, 8);
    sm_config_set_sideset_pin_base(&c, PIN_BE_REQ);
    sm_config_set_in_shift(&c, false, true, 18);
    sm_config_set_out_shift(&c, true, false, 32);
    pio_sm_set_pins_with_mask(pio_serve, sm_serve, 0, (1u << PIN_BE_REQ));
    pio_sm_set_pindirs_with_mask(pio_serve, sm_serve, 1u << PIN_BE_REQ, (1u << PIN_BE_REQ) | 0xffu);
    for (uint p = PIN_MD0; p < PIN_MD0 + 8; p++) {
        pio_gpio_init(pio_serve, p);
    }
    pio_gpio_init(pio_serve, PIN_BE_REQ);
    pio_sm_init(pio_serve, sm_serve, serve_offset_entry, &c);
    pio_sm_put(pio_serve, sm_serve, IMAGE_PREFIX);
    pio_sm_exec(pio_serve, sm_serve, pio_encode_pull(false, true));
    pio_sm_exec(pio_serve, sm_serve, pio_encode_mov(pio_x, pio_osr));
    write_table();
    set_serving(false);

    // io_drive (PIO0): drives replies to IN 0Eh/0Fh onto MD.
    sm_iodrv = claim_sm(pio_serve);
    uint off_iodrv = add_program(pio_serve, &io_drive_program);
    c = io_drive_program_get_default_config(off_iodrv);
    sm_config_set_out_pins(&c, PIN_MD0, 8);
    sm_config_set_out_shift(&c, true, false, 32);
    pio_sm_init(pio_serve, sm_iodrv, off_iodrv, &c);

    // addr_read, mem_write, io_snoop (PIO1): the three buffer enables, all off.
    const uint32_t en = (1u << PIN_NAEN_LO) | (1u << PIN_NAEN_HI) | (1u << PIN_NDATA_OE);
    sm_addr = claim_sm(pio_addr);
    off_addr = add_program(pio_addr, &addr_read_program);
    c = addr_read_program_get_default_config(off_addr);
    sm_config_set_sideset_pin_base(&c, PIN_NAEN_LO);
    sm_config_set_jmp_pin(&c, PIN_NMEMRD);
    sm_config_set_mov_status(&c, STATUS_IRQ_SET, 2);
    pio_sm_set_pins_with_mask(pio_addr, sm_addr, en, en);
    pio_sm_set_pindirs_with_mask(pio_addr, sm_addr, en, en);
    pio_gpio_init(pio_addr, PIN_NAEN_LO);
    pio_gpio_init(pio_addr, PIN_NAEN_HI);
    pio_gpio_init(pio_addr, PIN_NDATA_OE);
    pio_sm_init(pio_addr, sm_addr, off_addr, &c);

    sm_write = claim_sm(pio_addr);
    uint off_write = add_program(pio_addr, &mem_write_program);
    c = mem_write_program_get_default_config(off_write);
    sm_config_set_in_pin_base(&c, PIN_MD0);
    sm_config_set_sideset_pin_base(&c, PIN_NAEN_LO);
    sm_config_set_in_shift(&c, false, true, 24);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    pio_sm_init(pio_addr, sm_write, off_write, &c);

    sm_snoop = claim_sm(pio_addr);
    uint off_snoop = add_program(pio_addr, &io_snoop_program);
    c = io_snoop_program_get_default_config(off_snoop);
    sm_config_set_in_pin_base(&c, PIN_MD0);
    sm_config_set_sideset_pin_base(&c, PIN_NAEN_LO);
    sm_config_set_in_shift(&c, false, true, 16);
    pio_sm_init(pio_addr, sm_snoop, off_snoop, &c);

    set_delays();
    // Synchronisers bypassed on MD and the read strobe in PIO0; those plus
    // nIOWR in PIO1.
    pio_serve->input_sync_bypass = 0xffu | (1u << PIN_NMEMRD);
    pio_addr->input_sync_bypass = 0xffu | (1u << PIN_NMEMRD) | (1u << PIN_NIOWR);

    // DMA: pointer from serve's RX FIFO -> ch_data's read-address trigger;
    // ch_data copies the byte into serve's TX FIFO, then chains to ch_log,
    // which copies the pointer into the log.
    ch_ptr = claim_dma();
    ch_data = claim_dma();
    ch_log = claim_dma();
    memset(addr_log, 0xff, sizeof addr_log);

    dma_channel_config l = dma_channel_get_default_config(ch_log);
    channel_config_set_transfer_data_size(&l, DMA_SIZE_32);
    channel_config_set_read_increment(&l, false);
    channel_config_set_write_increment(&l, true);
    channel_config_set_ring(&l, true, 14);
    dma_channel_configure(ch_log, &l, addr_log, &dma_hw->ch[ch_data].read_addr, 1, false);

    dma_channel_config d = dma_channel_get_default_config(ch_data);
    channel_config_set_transfer_data_size(&d, DMA_SIZE_8);
    channel_config_set_read_increment(&d, false);
    channel_config_set_write_increment(&d, false);
    channel_config_set_high_priority(&d, true);
    channel_config_set_chain_to(&d, ch_log);
    dma_channel_configure(ch_data, &d, &pio_serve->txf[sm_serve], NULL, 1, false);

    dma_channel_config p = dma_channel_get_default_config(ch_ptr);
    channel_config_set_transfer_data_size(&p, DMA_SIZE_32);
    channel_config_set_read_increment(&p, false);
    channel_config_set_write_increment(&p, false);
    channel_config_set_dreq(&p, pio_get_dreq(pio_serve, sm_serve, false));
    channel_config_set_high_priority(&p, true);
    dma_channel_configure(ch_ptr, &p, &dma_hw->ch[ch_data].al3_read_addr_trig, &pio_serve->rxf[sm_serve],
        dma_encode_endless_transfer_count(), true);

    pio_sm_set_enabled(pio_serve, sm_serve, true);
    pio_sm_set_enabled(pio_serve, sm_iodrv, true);
    pio_sm_set_enabled(pio_addr, sm_addr, true);
    pio_sm_set_enabled(pio_addr, sm_write, true);
    pio_sm_set_enabled(pio_addr, sm_snoop, true);
}

// ---- core 1 --------------------------------------------------------------------------

#define FORCE_LOW (1u << (IO_BANK0_GPIO0_CTRL_OUTOVER_LSB + 1))
#define IORD_MASK (1u << PIN_NIORD)
#define IORD_EDGE_FALL (1u << ((PIN_NIORD % 8) * 4 + 2))

// How long U3 may stay on waiting for the strobe to end, in core cycles from
// the handler's entry. The SCLD stops the Z80's clock while it updates the
// screen, which stretches some IN cycles to 2.4 us (tspico-hardware
// firmware/bringup/README.md, "Long IN strobes"); the guard only keeps U3 from
// staying on if /IORD sticks low.
#define IO_TIMEOUT_CYC 1000   // 4 us at 250 MHz

// An IN is in progress (nIORD low). Read the port through U1; for 0Eh/0Fh put
// the reply on MD (io_drive) and U3 on until the strobe ends. About 600 ns
// before the Z80 samples the data.
static void __not_in_flash_func(handle_in)(void) {
    uint32_t t0c = m33_hw->dwt_cyccnt;
    io_ins++;
    hw_set_bits(&io_bank0_hw->io[PIN_NAEN_LO].ctrl, FORCE_LOW);   // U1: A7..A0 onto MD
    busy_wait_at_least_cycles(8);                                  // ~32 ns: U1 enable plus margin
    uint port = sio_hw->gpio_in & 0xff;
    hw_clear_bits(&io_bank0_hw->io[PIN_NAEN_LO].ctrl, FORCE_LOW);
    if ((port & 0xfe) == 0x0e) {
        uint8_t reply;
        if (port & 1) {
            reply = io_status;
        } else if ((int32_t)(txq_head - txq_tail) > 0) {
            reply = txq[txq_tail % TXQ_N];
            txq_tail++;
        } else {
            reply = 0x00;
        }
        pio_serve->txf[sm_iodrv] = reply;                              // io_drive: onto MD
        busy_wait_at_least_cycles(4);
        hw_set_bits(&io_bank0_hw->io[PIN_NDATA_OE].ctrl, FORCE_LOW);  // U3: MD onto the Z80's bus
        io_in_ours++;
        uint32_t dt = m33_hw->dwt_cyccnt - t0c;
        if (dt > respond_max) {
            respond_max = dt;
        }
    }
    // Wait for the strobe to end, with a guard so U3 can never stay on.
    while (!(sio_hw->gpio_in & IORD_MASK)) {
        if (m33_hw->dwt_cyccnt - t0c > IO_TIMEOUT_CYC) {
            io_in_late++;
            break;
        }
    }
    hw_clear_bits(&io_bank0_hw->io[PIN_NDATA_OE].ctrl, FORCE_LOW);
}

// A falling edge on nIORD interrupts core 1 wherever its loop is (polling left
// gaps of up to 370 ns, too many for an IN's 600 ns). Edges only, so a line held
// low in reset is never taken for INs; and never while the 2068 is held.
static void __not_in_flash_func(iord_isr)(void) {
    io_bank0_hw->intr[PIN_NIORD / 8] = IORD_EDGE_FALL;
    if (!held_2068) {
        handle_in();
    }
}

// Core 1's own vector table. Both cores start with core 0's, where MicroPython
// keeps machine.Pin's shared handler on IO_IRQ_BANK0 (in flash); core 1 needs
// iord_isr there instead. 16 system vectors plus the IRQs, aligned to the next
// power of two above the table's size.
#define CORE1_NVEC (16 + NUM_IRQS)
static uint32_t core1_vectors[CORE1_NVEC] __attribute__((aligned(512)));
static uint32_t core1_stack[1024];   // 4 KB

static void __not_in_flash_func(core1_main)(void) {
    // Setup may call flash code: core 0 waits in tsbus.start() until it is done.
    const uint32_t *v = (const uint32_t *)scb_hw->vtor;
    for (uint i = 0; i < CORE1_NVEC; i++) {
        core1_vectors[i] = v[i];
    }
    core1_vectors[16 + IO_IRQ_BANK0] = (uint32_t)iord_isr;
    scb_hw->vtor = (uintptr_t)core1_vectors;
    __dsb();
    __isb();

    m33_hw->demcr |= M33_DEMCR_TRCENA_BITS;
    m33_hw->dwt_ctrl |= M33_DWT_CTRL_CYCCNTENA_BITS;
    io_bank0_hw->intr[PIN_NIORD / 8] = IORD_EDGE_FALL;
    gpio_set_irq_enabled(PIN_NIORD, GPIO_IRQ_EDGE_FALL, true);   // for this core
    irq_set_priority(IO_IRQ_BANK0, 0);
    irq_set_enabled(IO_IRQ_BANK0, true);
    core1_ready = true;

    const uint32_t snoop_empty = 1u << (PIO_FSTAT_RXEMPTY_LSB + sm_snoop);
    const uint32_t write_empty = 1u << (PIO_FSTAT_RXEMPTY_LSB + sm_write);
    for (;;) {
        // I/O writes: the bank shadow, and OUTs to 0Eh/0Fh.
        if (!(pio_addr->fstat & snoop_empty)) {
            uint32_t w = pio_addr->rxf[sm_snoop];
            uint port = (w >> 8) & 0xff, data = w & 0xff;
            io_writes++;
            bool changed = false;
            if (port == 0xf4) {
                changed = sh_hsr != data;
                sh_hsr = (uint8_t)data;
            }
            if (port == 0xff) {
                changed = (sh_ff ^ data) & 0x80;
                sh_ff = (uint8_t)data;
            }
            if (changed) {
                write_table();
            }
            if ((port & 0xfe) == 0x0e) {
                io_status = 0x00;             // busy until the firmware answers
                io_outs_ours++;
                if (rxq_head - rxq_tail < RXQ_N) {
                    rxq[rxq_head % RXQ_N] = (uint16_t)((port & 1) << 8 | data);
                    __dmb();
                    rxq_head++;
                } else {
                    rxq_lost++;
                }
            }
            continue;
        }
        // Memory writes: into the DOCK image when the shadow maps the chunk to
        // the dock. The Z80 may read the byte back about a microsecond later.
        if (!(pio_addr->fstat & write_empty)) {
            uint32_t w = pio_addr->rxf[sm_write];
            uint addr = (w >> 8) & 0xffff;
            mem_writes++;
            if (dock_on && ((sh_hsr >> (addr >> 13)) & 1) && !(sh_ff & 0x80)) {
                ((uint8_t *)TSBUS_IMAGE_REGION)[4 * addr + SLOT_DOCK] = (uint8_t)w;
                dock_writes++;
            }
            continue;
        }
        // Count served reads by slot from the log.
        uint32_t now = (dma_hw->ch[ch_log].write_addr - (uint32_t)addr_log) / 4;
        if (ring_seen != now) {
            uint slot = addr_log[ring_seen] & 3;
            if (slot < 3) {
                served[slot]++;
            }
            ring_seen = (ring_seen + 1) & (LOG_N - 1);
        }
    }
}

// ---- holding the 2068 ------------------------------------------------------------------

static void hold_2068(bool hold) {
    if (!hold && held_2068) {
        // The SCLD powers up with both registers clear; assume that.
        sh_hsr = sh_ff = 0;
        write_table();
    }
    held_2068 = hold;
    gpio_put(PIN_RESET_HOLD, hold);
    gpio_set_dir(PIN_RESET_HOLD, GPIO_OUT);
}

// ---- the clock ----------------------------------------------------------------------------

// 250 MHz with the core at 1.20 V, as phase 1 ran: the byte has to be on MD
// well inside an opcode fetch. In the order machine.freq() uses: the regulator
// first, then the flash divider (MicroPython's, in RAM; at most 84 MHz, so 3),
// then the clock. clk_peri and USB run from the USB PLL and do not change.
static void bus_clock(void) {
    if (clock_get_hz(clk_sys) == BUS_CLOCK_HZ) {
        return;
    }
    vreg_set_voltage(VREG_VOLTAGE_1_20);
    mp_hal_delay_ms(2);
    rp2_flash_set_timing_for_freq(BUS_CLOCK_HZ);
    if (!set_sys_clock_khz(BUS_CLOCK_HZ / 1000, false)) {
        mp_raise_msg(&mp_type_RuntimeError, MP_ERROR_TEXT("tsbus: cannot set 250 MHz"));
    }
}

// ---- Python ------------------------------------------------------------------------------

static void require_started(void) {
    if (!started) {
        mp_raise_msg(&mp_type_RuntimeError, MP_ERROR_TEXT("tsbus not started"));
    }
}

// tsbus.start(): claim the PIO and DMA, start core 1. The 2068 stays held.
// Does nothing if already running (tsbus survives a soft reset).
static mp_obj_t tsbus_start(void) {
    if (started) {
        return mp_const_none;
    }
    if ((uintptr_t)&__GcHeapEnd > TSBUS_IMAGE_REGION) {
        mp_raise_msg(&mp_type_RuntimeError, MP_ERROR_TEXT("tsbus: the GC heap overlaps the image region"));
    }
    bus_clock();
    memset((void *)TSBUS_IMAGE_REGION, 0xff, IMAGE_SIZE);
    // The DMA chain answers each read: give it the bus over the cores.
    busctrl_hw->priority = BUSCTRL_BUS_PRIORITY_DMA_W_BITS | BUSCTRL_BUS_PRIORITY_DMA_R_BITS;
    hold_2068(true);
    bus_start();
    core1_ready = false;
    multicore_launch_core1_with_stack(core1_main, core1_stack, sizeof core1_stack);
    for (uint32_t t0 = mp_hal_ticks_ms(); !core1_ready;) {
        if (mp_hal_ticks_ms() - t0 > 100) {
            mp_raise_msg(&mp_type_RuntimeError, MP_ERROR_TEXT("tsbus: core 1 did not start"));
        }
    }
    started = true;
    return mp_const_none;
}
static MP_DEFINE_CONST_FUN_OBJ_0(tsbus_start_obj, tsbus_start);

// tsbus.load(slot, data): copy data into slot 0 (HOME), 1 (EXROM) or 2 (DOCK),
// repeated to fill its 64 KB. Takes effect at once, so load what the 2068 is
// running only while it is held.
static mp_obj_t tsbus_load(mp_obj_t slot_in, mp_obj_t data_in) {
    mp_int_t slot = mp_obj_get_int(slot_in);
    if (slot < SLOT_HOME || slot > SLOT_DOCK) {
        mp_raise_ValueError(MP_ERROR_TEXT("slot must be 0, 1 or 2"));
    }
    mp_buffer_info_t buf;
    mp_get_buffer_raise(data_in, &buf, MP_BUFFER_READ);
    if (buf.len == 0 || buf.len > 0x10000) {
        mp_raise_ValueError(MP_ERROR_TEXT("data must be 1 to 65536 bytes"));
    }
    const uint8_t *src = buf.buf;
    uint8_t *r = (uint8_t *)TSBUS_IMAGE_REGION;
    for (uint32_t a = 0, i = 0; a < 0x10000; a++) {
        r[4 * a + slot] = src[i];
        if (++i == buf.len) {
            i = 0;
        }
    }
    return mp_const_none;
}
static MP_DEFINE_CONST_FUN_OBJ_2(tsbus_load_obj, tsbus_load);

// tsbus.serve(on): /BE and U3 requests live, or shadow mode (the card follows
// every read without driving the 2068). Only while the 2068 is held.
static mp_obj_t tsbus_serve(mp_obj_t on_in) {
    require_started();
    if (!held_2068) {
        mp_raise_msg(&mp_type_RuntimeError, MP_ERROR_TEXT("hold the 2068 first"));
    }
    set_serving(mp_obj_is_true(on_in));
    return mp_const_none;
}
static MP_DEFINE_CONST_FUN_OBJ_1(tsbus_serve_obj, tsbus_serve);

// tsbus.exrom(on), tsbus.dock(on): serve the chunks the bank registers map to
// the EXROM (with /BE) or the DOCK (no /BE; writes stored).
static mp_obj_t tsbus_exrom(mp_obj_t on_in) {
    require_started();
    exrom_on = mp_obj_is_true(on_in);
    write_table();
    return mp_const_none;
}
static MP_DEFINE_CONST_FUN_OBJ_1(tsbus_exrom_obj, tsbus_exrom);

static mp_obj_t tsbus_dock(mp_obj_t on_in) {
    require_started();
    dock_on = mp_obj_is_true(on_in);
    write_table();
    return mp_const_none;
}
static MP_DEFINE_CONST_FUN_OBJ_1(tsbus_dock_obj, tsbus_dock);

// tsbus.hold(on): hold the 2068 in reset (RESET_HOLD high), or release it.
static mp_obj_t tsbus_hold(mp_obj_t on_in) {
    require_started();
    hold_2068(mp_obj_is_true(on_in));
    return mp_const_none;
}
static MP_DEFINE_CONST_FUN_OBJ_1(tsbus_hold_obj, tsbus_hold);

static void store(mp_obj_t d, qstr k, mp_uint_t v) {
    mp_obj_dict_store(d, MP_OBJ_NEW_QSTR(k), mp_obj_new_int_from_uint(v));
}

// tsbus.stats(): the counters, as a dict.
static mp_obj_t tsbus_stats(void) {
    mp_obj_t d = mp_obj_new_dict(16);
    store(d, MP_QSTR_home, served[SLOT_HOME]);
    store(d, MP_QSTR_exrom, served[SLOT_EXROM]);
    store(d, MP_QSTR_dock, served[SLOT_DOCK]);
    store(d, MP_QSTR_io_writes, io_writes);
    store(d, MP_QSTR_mem_writes, mem_writes);
    store(d, MP_QSTR_dock_writes, dock_writes);
    store(d, MP_QSTR_table_updates, table_updates);
    store(d, MP_QSTR_ins, io_ins);
    store(d, MP_QSTR_ins_ours, io_in_ours);
    store(d, MP_QSTR_outs_ours, io_outs_ours);
    store(d, MP_QSTR_late, io_in_late);
    store(d, MP_QSTR_respond_ns, (mp_uint_t)((uint64_t)respond_max * 1000000000u / BUS_CLOCK_HZ));
    store(d, MP_QSTR_rx_lost, rxq_lost);
    store(d, MP_QSTR_hsr, sh_hsr);
    store(d, MP_QSTR_ff, sh_ff);
    store(d, MP_QSTR_held, held_2068);
    return d;
}
static MP_DEFINE_CONST_FUN_OBJ_0(tsbus_stats_obj, tsbus_stats);

static const mp_rom_map_elem_t tsbus_module_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_tsbus) },
    { MP_ROM_QSTR(MP_QSTR_start), MP_ROM_PTR(&tsbus_start_obj) },
    { MP_ROM_QSTR(MP_QSTR_load), MP_ROM_PTR(&tsbus_load_obj) },
    { MP_ROM_QSTR(MP_QSTR_serve), MP_ROM_PTR(&tsbus_serve_obj) },
    { MP_ROM_QSTR(MP_QSTR_exrom), MP_ROM_PTR(&tsbus_exrom_obj) },
    { MP_ROM_QSTR(MP_QSTR_dock), MP_ROM_PTR(&tsbus_dock_obj) },
    { MP_ROM_QSTR(MP_QSTR_hold), MP_ROM_PTR(&tsbus_hold_obj) },
    { MP_ROM_QSTR(MP_QSTR_stats), MP_ROM_PTR(&tsbus_stats_obj) },
    { MP_ROM_QSTR(MP_QSTR_HOME), MP_ROM_INT(SLOT_HOME) },
    { MP_ROM_QSTR(MP_QSTR_EXROM), MP_ROM_INT(SLOT_EXROM) },
    { MP_ROM_QSTR(MP_QSTR_DOCK), MP_ROM_INT(SLOT_DOCK) },
};
static MP_DEFINE_CONST_DICT(tsbus_module_globals, tsbus_module_globals_table);

const mp_obj_module_t tsbus_module = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t *)&tsbus_module_globals,
};

MP_REGISTER_MODULE(MP_QSTR_tsbus, tsbus_module);
