romupdate.tap: romupdate.bas romupdate_code.tap
	zmakebas -n romupdate -a 1 -o - romupdate.bas | cat - romupdate_code.tap > romupdate.tap

dckupdate.tap: dckupdate.bas dckupdate_code.tap
	zmakebas -n dckupdate -a 1 -o - dckupdate.bas | cat - dckupdate_code.tap > dckupdate.tap
