#!/usr/bin/env python3
"""Build the upgrade UF2's payload.

    tools/build-upgrade.py OUT_DIR

writes OUT_DIR/upgrade_data.py (frozen into the upgrade UF2) and
OUT_DIR/updater.tap:

  * the updater tape: src/upgrade/loader.bas (tokenized by the vendored
    zmakebas, built here if needed) + src/upgrade/updater.bin as CODE at
    24576 (6000h);
  * IMG1: flash/manifest.json's slot 1 (the TS-2068 ROM, 32K);
  * IMG0: slot 0's lower 16K (the ZX Spectrum ROM; the updater leaves the
    upper half alone).

The ROMs come from the manifest, so the upgrade always installs what the
512K flash image would ship.
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def block(flag, content):
    body = bytes([flag]) + content
    x = 0
    for b in body:
        x ^= b
    body += bytes([x])
    return bytes([len(body) & 0xFF, len(body) >> 8]) + body


def zmakebas(tmp):
    exe = shutil.which("zmakebas")
    if exe:
        return exe
    exe = os.path.join(tmp, "zmakebas")
    subprocess.run(["cc", "-O2", "-w", "-o", exe,
                    os.path.join(ROOT, "tools", "zmakebas", "zmakebas.c")], check=True)
    return exe


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "build-upgrade")
    os.makedirs(out, exist_ok=True)
    man = json.load(open(os.path.join(ROOT, "flash", "manifest.json")))
    slots = {s["slot"]: s for s in man["slots"]}
    fdir = os.path.join(ROOT, "flash")
    img1 = open(os.path.join(fdir, slots[1]["file"]), "rb").read()
    img0 = open(os.path.join(fdir, slots[0]["file"]), "rb").read()[:0x4000]
    assert len(img1) == 0x8000 and len(img0) == 0x4000, (len(img1), len(img0))

    code = open(os.path.join(ROOT, "src", "upgrade", "updater.bin"), "rb").read()
    with tempfile.TemporaryDirectory() as tmp:
        prog = os.path.join(tmp, "loader.tap")
        subprocess.run([zmakebas(tmp), "-a", "10", "-n", "tsupdate", "-o", prog,
                        os.path.join(ROOT, "src", "upgrade", "loader.bas")], check=True)
        tape = open(prog, "rb").read()
    hdr = bytes([3]) + b"updater   " + bytes([len(code) & 0xFF, len(code) >> 8,
                                              0x00, 0x60, 0x00, 0x80])
    tape += block(0, hdr) + block(0xFF, code)
    open(os.path.join(out, "updater.tap"), "wb").write(tape)

    with open(os.path.join(out, "upgrade_data.py"), "w") as f:
        f.write("# Generated by tools/build-upgrade.py -- do not edit.\n")
        f.write("# slot 1: %s (crc32 %08X)\n" % (slots[1]["name"], zlib.crc32(img1)))
        f.write("# slot 0: %s, lower 16K (crc32 %08X)\n" % (slots[0]["name"], zlib.crc32(img0)))
        for name, data in (("TAPE", tape), ("IMG1", img1), ("IMG0", img0)):
            f.write("%s = %r\n" % (name, data))
        f.write("IMG1_CRC = 0x%08X\nIMG0_CRC = 0x%08X\n" % (zlib.crc32(img1), zlib.crc32(img0)))
    print("updater.tap %d bytes; IMG1 %08X; IMG0 %08X -> %s"
          % (len(tape), zlib.crc32(img1), zlib.crc32(img0), out))


if __name__ == "__main__":
    main()
