#!/usr/bin/env python3
"""Write src/TS/buildinfo.py, the build stamp the firmware reports.

Run before staging the frozen modules:

    python3 tools/gen-buildinfo.py

The output is generated, not committed (it is gitignored), and `tspico.py`
imports it behind a try/except so a build without this step still runs --
BUILD_VERSION just reads "unknown".

Deliberately NO timestamp. Two builds of the same commit produce the same
UF2, which matters in a repo that crc32-checks its images (tools/romdiff.py).
The build date is already in MicroPython's own banner.
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "src", "TS", "buildinfo.py")


def git(*args, default="unknown"):
    try:
        out = subprocess.run(("git",) + args, cwd=ROOT, capture_output=True,
                             text=True, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return default
    if out.returncode != 0:
        return default
    return out.stdout.strip() or default


def main():
    commit = git("rev-parse", "--short", "HEAD")

    # In CI HEAD is detached, so git reports "HEAD" for the branch. The
    # runner knows the real name; prefer it when it is set.
    branch = os.environ.get("GITHUB_REF_NAME") or git(
        "rev-parse", "--abbrev-ref", "HEAD", default="unknown")
    if branch == "HEAD":
        branch = "detached"

    # Uncommitted work means the UF2 does not match `commit`. buildinfo.py
    # itself is gitignored, so generating it does not make the tree dirty.
    dirty = bool(git("status", "--porcelain", default=""))

    body = (
        '# GENERATED by tools/gen-buildinfo.py -- do not edit, do not commit.\n'
        '# Frozen into the UF2 and reported by the boot stamp and tpi:info.\n'
        'COMMIT = "%s"\n'
        'BRANCH = "%s"\n'
        'DIRTY = %s\n'
    ) % (commit, branch, dirty)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(body)
    print("%s: COMMIT=%s BRANCH=%s DIRTY=%s" % (OUT, commit, branch, dirty))
    return 0


if __name__ == "__main__":
    sys.exit(main())
