#!/usr/bin/env bash
# Regenerate the TS-PICO ROM disassemblies under docs/rom-analysis/disasm/.
#
#   ./tools/romdisasm.sh
#
# Requires z80dasm (brew install z80dasm).
#
# Every image disassembles at org 0x0000 because file offset == Z80 address for
# all of them; the EXROM is a flat 16K occupying TS2068 chunks 0+1. See
# docs/rom-analysis/MEMORY_MAP.md.
#
# The baseline images are ROMs/GENUINE-*.bin (crc32 bf44ec3f / ae16233a). Other
# TS2068 ROM images are in circulation and are not interchangeable with these;
# run tools/romdiff.py to have every image crc32-checked.
#
# NOTE: these are LINEAR sweeps. Data tables, text and 0xFF filler decode as
# nonsense instructions, and a misaligned start desynchronises a whole region.
# Use them to locate code, not as ground truth -- prefer the hand-verified
# listings in the Markdown docs. See the caveats in docs/rom-analysis/README.md.

set -euo pipefail

cd "$(dirname "$0")/.."

OUT=docs/rom-analysis/disasm
SYMS=docs/rom-analysis/tspico-exrom-symbols.sym

command -v z80dasm >/dev/null || {
    echo "z80dasm not found. Install with: brew install z80dasm" >&2
    exit 1
}

mkdir -p "$OUT"

# image:output-basename
PLAIN="
TSPICO-11-exrom:tspico-11-exrom
TSPICO-15w-exrom:tspico-15w-exrom
TSPICO-11-home:tspico-home
GENUINE-2068-exrom.bin:genuine-2068-exrom
GENUINE-2068-home.bin:genuine-2068-home
"

for pair in $PLAIN; do
    src="ROMs/${pair%%:*}"
    name="${pair##*:}"
    [ -f "$src" ] || { echo "missing $src -- see docs/rom-analysis/README.md" >&2; exit 1; }
    z80dasm -a -l -t -g 0x0000 -o "$OUT/$name.asm" -s "$OUT/$name.sym" "$src" 2>/dev/null
    echo "  $OUT/$name.asm  ($(wc -l < "$OUT/$name.asm" | tr -d ' ') lines)"
done

# Labelled EXROM listings, using our curated symbol names. These are the ones
# worth reading: the v1.5w fix renders as `jp nz,YN_LOOP_GUARD` /
# `call WAIT_PICO_READY` instead of bare addresses.
for v in 11 15w; do
    z80dasm -a -l -t -g 0x0000 -S "$SYMS" \
            -o "$OUT/tspico-$v-exrom.labelled.asm" "ROMs/TSPICO-$v-exrom" 2>/dev/null
    echo "  $OUT/tspico-$v-exrom.labelled.asm  (labelled)"
done

echo
echo "TSPICO-11-home and TSPICO-15w-home are byte-identical -- only one HOME"
echo "listing (tspico-home.asm) is produced."

# ---- ROM 2.2 (src/rom/TSPICO-22.ROM at the v2.2.1 tag) ---------------------
# One 32K file: HOME at offset 0, EXROM at 4000h. The EXROM listing is
# labelled with the curated symbols above PLUS every label of the ROM 2.0
# patch (src/rom/patches/tspico-sync.asm, the code at 2300h) and the ROM 2.1
# module (src/rom/fdd/fddcmd.asm, the code at 3000h), taken from a fresh
# sjasmplus assembly so they can't drift from the sources. docs/reference/rom/
# cites this listing. Needs sjasmplus; skipped (with a note) without it.
#
# The merged symbol file is written next to the listings and is generated:
# edit docs/rom-analysis/tspico-exrom-symbols.sym or the .asm sources, not it.
# The listings are of ROM 2.2, which docs/reference/rom/ cites; the repo now
# holds ROM 2.3 (src/rom/TSPICO-23.ROM), so 2.2 comes from its release tag.
ROM22="$(mktemp)"
git show v2.2.1:src/rom/TSPICO-22.ROM > "$ROM22" 2>/dev/null || rm -f "$ROM22"
if [ -s "$ROM22" ]; then
    if command -v sjasmplus >/dev/null; then
        TMP="$(mktemp -d)"
        trap 'rm -rf "$TMP"' EXIT
        # fddcmd.asm's SAVEBIN writes to the CWD; tspico-sync.asm's OUTPUT does
        # too, and its INCBIN is found through -i. Nothing under src/ is touched.
        ( cd "$TMP" && sjasmplus --nologo --msg=none --sym=fdd.sym \
              "$OLDPWD/src/rom/fdd/fddcmd.asm" >/dev/null )
        ( cd "$TMP" && sjasmplus --nologo --msg=none -Wno-fileorg --sym=sync.sym \
              -i"$OLDPWD/src/rom" "$OLDPWD/src/rom/patches/tspico-sync.asm" >/dev/null )
        MERGED="$OUT/tspico-22-exrom-symbols.sym"
        {
            echo "; GENERATED by tools/romdisasm.sh -- do not edit."
            echo "; = docs/rom-analysis/tspico-exrom-symbols.sym (the curated names, v1.1+)"
            echo ";   + the labels of src/rom/patches/tspico-sync.asm (ROM 2.0, 2300h)"
            echo ";   + the labels of src/rom/fdd/fddcmd.asm (ROM 2.1, 3000h)"
            echo "; Only values in 0100h-3FFFh are kept: everything else is a constant"
            echo "; or a RAM address, not an EXROM label. EQUs the sources mark"
            echo "; \"; HOME\" are dropped too: a HOME address is not an EXROM label."
            grep -E '^[A-Za-z_][A-Za-z0-9_.]*:[[:space:]]*equ' "$SYMS"
            # "NAME: EQU 0x0000XXXX" -> "NAME:\tequ 0xXXXX", EXROM addresses only
            python3 - "$TMP/sync.sym" "$TMP/fdd.sym" -- \
                src/rom/patches/tspico-sync.asm src/rom/fdd/fddcmd.asm <<'PY'
import re, sys
args = sys.argv[1:]
syms, sources = args[:args.index("--")], args[args.index("--") + 1:]
# fddcmd.asm's H_EXPT_STR (1BEFh) is a HOME routine; merged as an EXROM label
# it named the middle of STATUS_TO_REPORT's lead-in. The sources say which
# EQUs are HOME addresses ("NAME EQU $xxxx ; HOME: ..."); leave those out.
home = set()
for src in sources:
    for line in open(src):
        m = re.match(r"\s*([A-Za-z_][A-Za-z0-9_]*)\s+EQU\s+\S+\s*;\s*HOME\b", line, re.I)
        if m:
            home.add(m.group(1))
for path in syms:
    for line in open(path):
        name, _, rest = line.partition(":")
        if "EQU" not in rest or name.strip() in home:
            continue
        v = int(rest.split()[-1], 16)
        if 0x100 <= v <= 0x3FFF:
            print("%s:\tequ 0x%04x" % (name.strip(), v))
PY
        } | awk '!seen[$1]++' > "$MERGED"
        dd if="$ROM22" of="$TMP/home.bin" bs=16384 count=1 2>/dev/null
        dd if="$ROM22" of="$TMP/exrom.bin" bs=16384 skip=1 count=1 2>/dev/null
        z80dasm -a -l -t -g 0x0000 -o "$OUT/tspico-22-home.asm" -s "$OUT/tspico-22-home.sym" "$TMP/home.bin" 2>/dev/null
        z80dasm -a -l -t -g 0x0000 -S "$MERGED" -o "$OUT/tspico-22-exrom.labelled.asm" "$TMP/exrom.bin" 2>/dev/null
        echo
        echo "  $OUT/tspico-22-home.asm  ($(wc -l < "$OUT/tspico-22-home.asm" | tr -d ' ') lines, ROM 2.2 HOME)"
        echo "  $OUT/tspico-22-exrom.labelled.asm  (ROM 2.2 EXROM, $(grep -c equ "$MERGED") labels)"
    else
        echo "sjasmplus not found: the ROM 2.2 listings were not regenerated." >&2
    fi
fi
